// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file packet.proto (package system, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { RoomUser } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file packet.proto.
 */
export const file_packet: GenFile = /*@__PURE__*/
  fileDesc("CgxwYWNrZXQucHJvdG8SBnN5c3RlbSIuCgtBdXRoUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRINCgV0b2tlbhgCIAEoCSIpChNBdXRoUmVzcG9uc2VTdWNjZXNzEhIKCnNlc3Npb25faWQYASABKAMieQoRQXV0aFJlc3BvbnNlRXJyb3ISLAoEdHlwZRgBIAEoDjIeLnN5c3RlbS5BdXRoUmVzcG9uc2VFcnJvci5UeXBlIjYKBFR5cGUSFwoTSU5WQUxJRF9DUkVERU5USUFMUxAAEhUKEUFMUkVBRFlfTE9HR0VEX0lOEAEiIwoPSm9pblJvb21SZXF1ZXN0EhAKCHJvb21fa2V5GAEgASgJIjMKEEpvaW5Sb29tUmVzcG9uc2USHwoFdXNlcnMYASADKAsyEC5zeXN0ZW0uUm9vbVVzZXIqoQEKClBhY2tldFR5cGUSEAoMQVVUSF9SRVFVRVNUEAASGQoVQVVUSF9SRVNQT05TRV9TVUNDRVNTEAESFwoTQVVUSF9SRVNQT05TRV9FUlJPUhACEhUKEUpPSU5fUk9PTV9SRVFVRVNUEAMSFgoSSk9JTl9ST09NX1JFU1BPTlNFEAQSDwoLVVNFUl9KT0lORUQQBRINCglVU0VSX0xFRlQQBmIGcHJvdG8z", [file_common]);

/**
 * @generated from message system.AuthRequest
 */
export type AuthRequest = Message<"system.AuthRequest"> & {
  /**
   * The user's username.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * Unused for now.
   *
   * @generated from field: string token = 2;
   */
  token: string;
};

/**
 * Describes the message system.AuthRequest.
 * Use `create(AuthRequestSchema)` to create a new message.
 */
export const AuthRequestSchema: GenMessage<AuthRequest> = /*@__PURE__*/
  messageDesc(file_packet, 0);

/**
 * @generated from message system.AuthResponseSuccess
 */
export type AuthResponseSuccess = Message<"system.AuthResponseSuccess"> & {
  /**
   * The session ID.
   *
   * @generated from field: int64 session_id = 1;
   */
  sessionId: bigint;
};

/**
 * Describes the message system.AuthResponseSuccess.
 * Use `create(AuthResponseSuccessSchema)` to create a new message.
 */
export const AuthResponseSuccessSchema: GenMessage<AuthResponseSuccess> = /*@__PURE__*/
  messageDesc(file_packet, 1);

/**
 * @generated from message system.AuthResponseError
 */
export type AuthResponseError = Message<"system.AuthResponseError"> & {
  /**
   * The error type.
   *
   * @generated from field: system.AuthResponseError.Type type = 1;
   */
  type: AuthResponseError_Type;
};

/**
 * Describes the message system.AuthResponseError.
 * Use `create(AuthResponseErrorSchema)` to create a new message.
 */
export const AuthResponseErrorSchema: GenMessage<AuthResponseError> = /*@__PURE__*/
  messageDesc(file_packet, 2);

/**
 * @generated from enum system.AuthResponseError.Type
 */
export enum AuthResponseError_Type {
  /**
   * The provided credentials were invalid.
   *
   * @generated from enum value: INVALID_CREDENTIALS = 0;
   */
  INVALID_CREDENTIALS = 0,

  /**
   * The specified user is already logged in.
   *
   * @generated from enum value: ALREADY_LOGGED_IN = 1;
   */
  ALREADY_LOGGED_IN = 1,
}

/**
 * Describes the enum system.AuthResponseError.Type.
 */
export const AuthResponseError_TypeSchema: GenEnum<AuthResponseError_Type> = /*@__PURE__*/
  enumDesc(file_packet, 2, 0);

/**
 * @generated from message system.JoinRoomRequest
 */
export type JoinRoomRequest = Message<"system.JoinRoomRequest"> & {
  /**
   * @generated from field: string room_key = 1;
   */
  roomKey: string;
};

/**
 * Describes the message system.JoinRoomRequest.
 * Use `create(JoinRoomRequestSchema)` to create a new message.
 */
export const JoinRoomRequestSchema: GenMessage<JoinRoomRequest> = /*@__PURE__*/
  messageDesc(file_packet, 3);

/**
 * @generated from message system.JoinRoomResponse
 */
export type JoinRoomResponse = Message<"system.JoinRoomResponse"> & {
  /**
   * @generated from field: repeated system.RoomUser users = 1;
   */
  users: RoomUser[];
};

/**
 * Describes the message system.JoinRoomResponse.
 * Use `create(JoinRoomResponseSchema)` to create a new message.
 */
export const JoinRoomResponseSchema: GenMessage<JoinRoomResponse> = /*@__PURE__*/
  messageDesc(file_packet, 4);

/**
 * @generated from enum system.PacketType
 */
export enum PacketType {
  /**
   * @generated from enum value: AUTH_REQUEST = 0;
   */
  AUTH_REQUEST = 0,

  /**
   * @generated from enum value: AUTH_RESPONSE_SUCCESS = 1;
   */
  AUTH_RESPONSE_SUCCESS = 1,

  /**
   * @generated from enum value: AUTH_RESPONSE_ERROR = 2;
   */
  AUTH_RESPONSE_ERROR = 2,

  /**
   * @generated from enum value: JOIN_ROOM_REQUEST = 3;
   */
  JOIN_ROOM_REQUEST = 3,

  /**
   * @generated from enum value: JOIN_ROOM_RESPONSE = 4;
   */
  JOIN_ROOM_RESPONSE = 4,

  /**
   * @generated from enum value: USER_JOINED = 5;
   */
  USER_JOINED = 5,

  /**
   * @generated from enum value: USER_LEFT = 6;
   */
  USER_LEFT = 6,
}

/**
 * Describes the enum system.PacketType.
 */
export const PacketTypeSchema: GenEnum<PacketType> = /*@__PURE__*/
  enumDesc(file_packet, 0);

